app/main/forms.py
from flask_wtf import FlaskForm  # type: ignore
from govuk_frontend_wtf.wtforms_widgets import GovRadioInput, GovSubmitInput  # type: ignore
from wtforms.fields import RadioField, SubmitField  # type: ignore
from wtforms.validators import InputRequired  # type: ignore


class CookiesForm(FlaskForm):
    """Form for managing cookie preferences."""

    functional: RadioField = RadioField(
        "Do you want to accept functional cookies?",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Select yes if you want to accept functional cookies")],
        choices=[("no", "No"), ("yes", "Yes")],
        default="no",
    )
    analytics: RadioField = RadioField(
        "Do you want to accept analytics cookies?",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Select yes if you want to accept analytics cookies")],
        choices=[("no", "No"), ("yes", "Yes")],
        default="no",
    )
    save: SubmitField = SubmitField("Save cookie settings", widget=GovSubmitInput())

app/__init__.py
from typing import Type

from flask import Flask
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect  # type: ignore[import]
from govuk_frontend_wtf.main import WTFormsHelpers  # type: ignore[import]
from jinja2 import ChoiceLoader, PackageLoader, PrefixLoader
from werkzeug.middleware.proxy_fix import ProxyFix

from config import Config

# Initialize Flask extensions. These are initialized here for easier access.
csrf: CSRFProtect = CSRFProtect()
db: SQLAlchemy = SQLAlchemy()
limiter: Limiter = Limiter(get_remote_address, default_limits=["2 per second", "60 per minute"])
migrate: Migrate = Migrate()


def create_app(config_class: Type[Config] = Config) -> Flask:
    """Create and configure the Flask application.

    Args:
        config_class: The configuration class to use (defaults to `Config`).

    Returns:
        A configured Flask application instance.
    """
    app: Flask = Flask(__name__)  # type: ignore[assignment]
    app.config.from_object(config_class)
    app.jinja_env.globals["govukRebrand"] = True
    app.jinja_env.lstrip_blocks = True
    app.jinja_env.trim_blocks = True

    # Configure Jinja2 template loader to search in multiple locations.
    app.jinja_loader = ChoiceLoader(
        [
            PackageLoader("app"),  # Load templates from the 'app' package.
            PrefixLoader(
                {
                    "govuk_frontend_jinja": PackageLoader("govuk_frontend_jinja"),
                    "govuk_frontend_wtf": PackageLoader("govuk_frontend_wtf"),
                }
            ),
        ]
    )

    # Use ProxyFix middleware to handle proxies correctly.
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1)  # type: ignore[method-assign]

    # Initialize Flask extensions
    csrf.init_app(app)
    db.init_app(app)
    limiter.init_app(app)
    migrate.init_app(app, db)
    WTFormsHelpers(app)

    # Register blueprints. These define different sections of the application.
    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    return app


from app import models  # noqa: E402,F401

app/main/__init__.py
from flask import Blueprint

bp: Blueprint = Blueprint("main", __name__, template_folder="../templates/main")

from app.main import routes  # noqa: E402,F401

app/main/routes.py
from typing import Union

from flask import (
    Response,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_wtf.csrf import CSRFError  # type: ignore
from werkzeug.exceptions import HTTPException

from app.main import bp
from app.main.forms import CookiesForm


@bp.route("/", methods=["GET"])
def index() -> str:
    """Render the index page."""
    return render_template("index.html")


@bp.route("/accessibility", methods=["GET"])
def accessibility() -> str:
    """Render the accessibility statement page."""
    return render_template("accessibility.html")


@bp.route("/cookies", methods=["GET", "POST"])
def cookies() -> Union[str, Response]:
    """Handle GET and POST requests for managing cookie preferences."""
    form: CookiesForm = CookiesForm()
    # Initialize cookie settings. Defaults to rejecting all cookies.
    functional: str = "no"
    analytics: str = "no"

    if form.validate_on_submit():
        # Update cookie settings based on form submission
        functional = form.functional.data
        analytics = form.analytics.data
        # Create flash message confirmation before rendering template
        flash("You've set your cookie preferences.", "success")
        # Create the response so we can set cookies before returning
        response: Response = make_response(render_template("cookies.html", form=form))

        # Set individual cookies in the response
        response.set_cookie("functional", functional, max_age=31557600, secure=True, samesite="Lax")
        response.set_cookie("analytics", analytics, max_age=31557600, secure=True, samesite="Lax")

        return response
    elif request.method == "GET":
        # Retrieve existing cookie settings if present
        functional = request.cookies.get("functional", "no")
        analytics = request.cookies.get("analytics", "no")

        # Pre-populate form with existing settings
        form.functional.data = functional
        form.analytics.data = analytics

    return render_template("cookies.html", form=form)


@bp.route("/privacy", methods=["GET"])
def privacy() -> str:
    """Render the privacy policy page."""
    return render_template("privacy.html")


@bp.route("/health", methods=["GET"])
def health() -> Response:
    """Route for healthchecks"""
    return make_response("OK", 200)


@bp.app_errorhandler(HTTPException)
def handle_http_exception(error: HTTPException) -> Response:
    """Handle HTTP exceptions and render appropriate error template."""
    return make_response(render_template(f"{error.code}.html"), error.code)


@bp.app_errorhandler(CSRFError)
def handle_csrf_error(error: CSRFError) -> Response:
    """Handle CSRF errors and display a flash message."""
    flash("The form you were submitting has expired. Please try again.")
    return make_response(redirect(url_for("main.index")))

app/templates/base.html
{%- extends 'govuk_frontend_jinja/template.html' -%}

{%- from 'govuk_frontend_jinja/components/cookie-banner/macro.html' import govukCookieBanner-%}
{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary-%}
{%- from 'govuk_frontend_jinja/components/notification-banner/macro.html' import govukNotificationBanner -%}
{%- from 'govuk_frontend_jinja/components/phase-banner/macro.html' import govukPhaseBanner -%}
{%- from 'govuk_frontend_jinja/components/service-navigation/macro.html' import govukServiceNavigation -%}

{%- set assetPath = "/static/assets" -%}

{%- block pageTitle -%}{{config['SERVICE_NAME']}} – GOV.UK{%- endblock -%}

{%- block head -%}
  <meta name="description" content="{{config['SERVICE_NAME']}}">
  <meta name="keywords" content="">
  <meta name="author" content="{{config['DEPARTMENT_NAME']}}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.min.css') }}" />
{%- endblock -%}

{%- block bodyStart -%}
  {%- if "functional" not in request.cookies or "analytics" not in request.cookies -%}
    {%- set html -%}
      <p class="govuk-body">We use some essential cookies to make this service work.</p>
      <p class="govuk-body">We’d like to set additional cookies so we can remember your settings, understand how people use the service and make improvements.</p>
    {%- endset -%}

    {%- set acceptHtml -%}
      <p class="govuk-body">You’ve accepted additional cookies. You can <a class="govuk-link" href="{{ url_for('main.cookies') }}">change your cookie settings</a> at any time.</p>
    {%- endset -%}

    {%- set rejectHtml -%}
      <p class="govuk-body">You’ve rejected additional cookies. You can <a class="govuk-link" href="{{ url_for('main.cookies') }}">change your cookie settings</a> at any time.</p>
    {%- endset -%}

    {{ govukCookieBanner({
      'ariaLabel': "Cookies on " ~ config['SERVICE_NAME'],
      'attributes': {
        'id': "cookie-banner"
      },
      'messages': [
        {
          'attributes': {
            'id': "default-message"
          },
          'headingText': "Cookies on " ~ config['SERVICE_NAME'],
          'html': html,
          'actions': [
            {
              'attributes': {
                'id': "accept-cookies"
              },
              'text': "Accept additional cookies",
              'type': "button",
              'name': "cookies",
              'value': "accept"
            },
            {
              'attributes': {
                'id': "reject-cookies"
              },
              'text': "Reject additional cookies",
              'type': "button",
              'name': "cookies",
              'value': "reject"
            },
            {
              'text': "View cookies",
              'href': url_for('main.cookies')
            }
          ]
        },
        {
          'attributes': {
            'id': "accepted-message"
          },
          'html': acceptHtml,
          'role': "alert",
          'hidden': true,
          'actions': [
            {
              'attributes': {
                'id': "accepted-hide"
              },
              'text': "Hide this message"
            }
          ]
        },
        {
          'attributes': {
            'id': "rejected-message"
          },
          'html': rejectHtml,
          'role': "alert",
          'hidden': true,
          'actions': [
            {
              'attributes': {
                'id': "rejected-hide"
              },
              'text': "Hide this message"
            }
          ]
        }
      ]
    }) }}
  {%- endif -%}
{%- endblock -%}

{%- block header -%}
  {{ govukHeader({}) }}
  {{ govukServiceNavigation({
    'serviceName': config['SERVICE_NAME'],
    'serviceUrl': url_for('main.index'),
    'navigation': [
      {
        'href': "#",
        'text': "Navigation item 1"
      },
      {
        'href': "#",
        'text': "Navigation item 2",
        'active': true
      },
      {
        'href': "#",
        'text': "Navigation item 3"
      }
    ]
  }) }}
{%- endblock -%}

{%- block beforeContent -%}
  {{ govukPhaseBanner({
    'tag': {
      'text': config['SERVICE_PHASE']
    },
    'html': 'This is a new service – your <a class="govuk-link" href="mailto:' + config['CONTACT_EMAIL'] + '">feedback</a> will help us to improve it.'
  }) }}
{%- endblock -%}

{%- block content -%}
  {%- if form and form.errors -%}
    {{ govukErrorSummary(wtforms_errors(form)) }}
  {%- endif -%}

  {%- with messages = get_flashed_messages(with_categories=true) -%}
    {%- if messages -%}
      {%- for category, message in messages -%}
          {{ govukNotificationBanner({'type': category, 'html': message}) }}
      {%- endfor -%}
    {%- endif -%}
  {%- endwith -%}
{%- endblock -%}

{%- block footer -%}
  {{ govukFooter({
    'meta': {
      'items': [
        {
          'href': url_for('main.accessibility'),
          'text': "Accessibility"
        },
        {
          'href': url_for('main.cookies'),
          'text': "Cookies"
        },
        {
            'href': url_for('main.privacy'),
            'text': "Privacy"
          }
      ],
      'html': 'Built by <a href="' + config['DEPARTMENT_URL'] +'" class="govuk-footer__link">' + config['DEPARTMENT_NAME'] + '</a>'
    }
  }) }}
{%- endblock -%}

{%- block bodyEnd -%}
  <script type="module" src="{{ url_for('static', filename='main.min.js') }}"></script>
{%- endblock -%}

app/templates/main/429.html
{%- extends "base.html" -%}

{%- block pageTitle -%}Too many requests – {{config['SERVICE_NAME']}} – GOV.UK{%- endblock -%}

{%- set mainClasses = "govuk-main-wrapper--l" -%}

{%- block content -%}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Sorry, there is a problem</h1>
        <p class="govuk-body">There have been too many attempts to access this page.</p>
        <p class="govuk-body">Try again later.</p>
    </div>
</div>
{%- endblock -%}

app/templates/main/503.html
{%- extends "base.html" -%}

{%- block pageTitle -%}Sorry, the service is unavailable – {{config['SERVICE_NAME']}} – GOV.UK{%- endblock -%}

{%- set mainClasses = "govuk-main-wrapper--l" -%}

{%- block content -%}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Sorry, the service is unavailable</h1>
        <p class="govuk-body">You will be able to use the service from 9am on Monday 19&nbsp;November&nbsp;2018.</p>
    </div>
</div>
{%- endblock -%}

app/templates/main/accessibility.html
{%- extends "base.html" -%}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}

{%- block pageTitle -%}Accessibility statement – {{config['SERVICE_NAME']}} – GOV.UK{%- endblock -%}

{%- block beforeContent -%}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{%- endblock -%}

{%- block content -%}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <h1 class="govuk-heading-xl">Accessibility statement for {{config['SERVICE_NAME']}}</h1>

    <p class="govuk-body">This accessibility statement applies to {{config['SERVICE_URL']}}.</p>
    
    <p class="govuk-body">This website is run by {{config['DEPARTMENT_NAME']}}. We want as many people as possible to be able
      to use this website. For example, that means you should be able to:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>change colours, contrast levels and fonts</li>
      <li>zoom in up to 300% without the text spilling off the screen</li>
      <li>navigate most of the website using just a keyboard</li>
      <li>navigate most of the website using speech recognition software</li>
      <li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and
        VoiceOver)</li>
    </ul>
    <p class="govuk-body">We’ve also made the website text as simple as possible to understand.</p>
    <p class="govuk-body"><a class="govuk-link" href="https://mcmw.abilitynet.org.uk/">AbilityNet</a> has advice on making your device easier to use if you have a disability.</p>

    <h3 class="govuk-heading-m">How accessible this website is</h3>

    <p class="govuk-body">We know some parts of this website are not fully accessible:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>the text will not reflow in a single column when you change the size of the browser window</li>
      <li>you cannot modify the line height or spacing of text</li>
      <li>most older PDF documents are not fully accessible to screen reader software</li>
      <li>live video streams do not have captions</li>
      <li>some of our online forms are difficult to navigate using just a keyboard</li>
      <li>you cannot skip to the main content when using a screen reader</li>
      <li>there’s a limit to how far you can magnify the map on our ‘contact us’ page</li>
    </ul>
    
    <h3 class="govuk-heading-m">Feedback and contact information</h3>
    
    <p class="govuk-body">If you need information on this website in a different format like accessible PDF, large
      print, easy read, audio recording or braille:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>email {{config['CONTACT_EMAIL']}}</li>
      <li>call {{config['CONTACT_PHONE']}}</li>
      <li>[add any other contact details]</li>
    </ul>
    <p class="govuk-body">We’ll consider your request and get back to you in [number] days.</p>
    <p class="govuk-body">If you cannot view the map on our ‘contact us’ page, call or email us [add link to contact
      details page] for directions.</p>
    
    <h3 class="govuk-heading-m">Reporting accessibility problems with this website</h3>

    <p class="govuk-body">We’re always looking to improve the accessibility of this website. If you find any problems
      not listed on this page or think we’re not meeting accessibility requirements, contact: [provide both details of
      how to report these issues to your organisation, and contact details for the unit or person responsible for
      dealing with these reports].</p>
    
    <h3 class="govuk-heading-m">Enforcement procedure</h3>
    
    <p class="govuk-body">The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector
      Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility
      regulations’). If you’re not happy with how we respond to your complaint, <a class="govuk-link"
        href="https://www.equalityadvisoryservice.com/">contact the Equality Advisory and
        Support Service (EASS)</a>.</p>

    <h2 class="govuk-heading-l">Contacting us by phone or visiting us in person</h2>

    <p class="govuk-body">We provide a text relay service for people who are D/deaf, hearing impaired or have a speech
      impediment.</p>
    <p class="govuk-body">Our offices have audio induction loops, or if you contact us before your visit we can arrange
      a British Sign Language (BSL) interpreter.</p>
    <p class="govuk-body">Find out how to contact us [add link to contact details page].</p>

    <h2 class="govuk-heading-l">Technical information about this website’s accessibility</h2>

    <p class="govuk-body">{{config['DEPARTMENT_NAME']}} is committed to making its website accessible, in accordance with the
      Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.</p>
    
    <h3 class="govuk-heading-m">Compliance status</h3>

    <p class="govuk-body">This website is fully compliant with the <a href="https://www.w3.org/TR/WCAG21/" class="govuk-link">Web Content Accessibility Guidelines version 2.1</a> AA
      standard.</p>
    <p class="govuk-body">This website is partially compliant with the <a href="https://www.w3.org/TR/WCAG21/" class="govuk-link">Web Content Accessibility Guidelines version 2.1</a>
      AA standard, due to [insert one of the following: ‘the non-compliances’, ‘the exemptions’ or ‘the non-compliances
      and exemptions’] listed below.</p>
    <p class="govuk-body">This website is not compliant with the <a href="https://www.w3.org/TR/WCAG21/" class="govuk-link">Web Content Accessibility Guidelines version 2.1</a> AA
      standard. The [insert one of the following: ‘non-compliances’, ‘exemptions’ or ‘non-compliances and exemptions’]
      are listed below.</p>

    <h2 class="govuk-heading-l">Non-accessible content</h2>

    <p class="govuk-body">The content listed below is non-accessible for the following reasons.</p>

    <h3 class="govuk-heading-m">Non-compliance with the accessibility regulations</h3>

    <p class="govuk-body">Some images do not have a text alternative, so people using a screen reader cannot access the
      information. This fails WCAG 2.1 success criterion 1.1.1 (non-text content).</p>

    <p class="govuk-body">We plan to add text alternatives for all images by September 2020. When we publish new content
      we’ll make sure our use of images meets accessibility standards.</p>
    
    <h3 class="govuk-heading-m">Disproportionate burden</h3>

    <h3 class="govuk-heading-s">Navigation and accessing information</h3>

    <p class="govuk-body">There’s no way to skip the repeated content in the page header (for example, a ‘skip to main
      content’ option).</p>

    <p class="govuk-body">It’s not always possible to change the device orientation from horizontal to vertical without
      making it more difficult to view the content.</p>

    <p class="govuk-body">It’s not possible for users to change text size without some of the content overlapping.</p>
    
    <h3 class="govuk-heading-s">Interactive tools and transactions</h3>

    <p class="govuk-body">Some of our interactive forms are difficult to navigate using a keyboard. For example, because
      some form controls are missing a ‘label’ tag.</p>

    <p class="govuk-body">Our forms are built and hosted through third party software and ‘skinned’ to look like our
      website.</p>

    <p class="govuk-body">We’ve assessed the cost of fixing the issues with navigation and accessing information, and
      with interactive tools and transactions. We believe that doing so now would be a <a href="http://www.legislation.gov.uk/uksi/2018/952/regulation/7/made" class="govuk-link">disproportionate burden</a> within
      the meaning of the accessibility regulations. We will make another assessment when the supplier contract is up for
      renewal, likely to be in [rough timing].</p>

    <h3 class="govuk-heading-m">Content that’s not within the scope of the accessibility regulations</h3>

    <h3 class="govuk-heading-s">PDFs and other documents</h3>

    <p class="govuk-body">Some of our PDFs and Word documents are essential to providing our services. For example, we
      have PDFs with information on how users can access our services, and forms published as Word documents. By
      September 2020, we plan to either fix these or replace them with accessible HTML pages.</p>

    <p class="govuk-body">The accessibility regulations <a href="http://www.legislation.gov.uk/uksi/2018/952/regulation/4/made" class="govuk-link">do not require us to fix PDFs or other documents published
      before 23 September 2018</a> if they’re not essential to providing our services. For example, we do not plan to fix
      [example of non-essential document].</p>

    <p class="govuk-body">Any new PDFs or Word documents we publish will meet accessibility standards.</p>
    
    <h3 class="govuk-heading-s">Live video</h3>

    <p class="govuk-body">We do not plan to add captions to live video streams because live video is <a href="http://www.legislation.gov.uk/uksi/2018/952/regulation/4/made" class="govuk-link">exempt from meeting
      the accessibility regulations</a>.</p>

    <h2 class="govuk-heading-l">What we’re doing to improve accessibility</h2>

    <p class="govuk-body">Our accessibility roadmap [add link to roadmap] shows how and when we plan to improve
      accessibility on this website.</p>
    
    <h2 class="govuk-heading-l">Preparation of this accessibility statement</h2>

    <p class="govuk-body">This statement was prepared on [date when it was first published]. It was last reviewed on
      [date when it was last reviewed].</p>

    <p class="govuk-body">This website was last tested on [date]. The test was carried out by [add name of organisation
      that carried out test, or indicate that you did your own testing].</p>

    <p class="govuk-body">We used this approach to deciding on a sample of pages to test [add link to explanation of how
      you decided which pages to test].</p>

    <p class="govuk-body">You can read the full accessibility test report [add link to report].</p>
  </div>
</div>
{%- endblock -%}

app/templates/main/cookies.html
{%- extends "base.html" -%}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}
{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}

{%- block pageTitle -%}{%- if form.errors -%}Error: {%- endif -%}Cookies – {{config['SERVICE_NAME']}} – GOV.UK{%- endblock -%}

{%- block beforeContent -%}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{%- endblock -%}

{%- block content -%}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <h1 class="govuk-heading-l">Cookies</h1>
    <p class="govuk-body">Cookies are small files saved on your phone, tablet or computer when you visit a website.
    </p>
    <p class="govuk-body">We use cookies to make {{config['SERVICE_NAME']}} work and collect information about how you use our
      service.</p>

    <h2 class="govuk-heading-m">Essential cookies</h2>
    <p class="govuk-body">Essential cookies keep your information secure while you use {{config['SERVICE_NAME']}}. We do not need
      to ask permission to use them.</p>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'cookie_policy'}, {'text': 'Saves your cookie consent settings'}, {'text': '1 year'}],
          [{'text': 'session'}, {'text': 'Temporary storage'}, {'text': 'Session'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Functional cookies</h2>
    <p class="govuk-body">Functional cookies allow you to take advantage of some functionality, for example remembering
      settings between visits. The service will work without them.</p>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'foo'}, {'text': 'bar'}, {'text': 'baz'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Analytics cookies</h2>
    <p class="govuk-body">With your permission, we use Google Analytics to collect data about how you use {{config['SERVICE_NAME']}}. This
      information helps us to improve our service.</p>
    <p class="govuk-body">Google is not allowed to use or share our analytics data with anyone.</p>
    <p class="govuk-body">Google Analytics stores anonymised information about:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>how you got to {{config['SERVICE_NAME']}}</li>
      <li>the pages you visit on {{config['SERVICE_NAME']}} and how long you spend on them</li>
      <li>any errors you see while using {{config['SERVICE_NAME']}}</li>
    </ul>
    {{ govukTable(
      {
        'head': [{'text': 'Name'}, {'text': 'Purpose'}, {'text': 'Expires'}],
        'rows': [
          [{'text': 'foo'}, {'text': 'bar'}, {'text': 'baz'}]
        ]
      }
    )}}

    <h2 class="govuk-heading-m">Change your cookie settings</h2>
    <form action="" method="post" novalidate>
      {{ form.csrf_token }}
      {{ form.functional }}
      {{ form.analytics }}
      {{ form.save }}
    </form>
  </div>
</div>
{%- endblock -%}

app/templates/main/index.html
{%- extends "base.html" -%}

{%- block beforeContent -%}
{{ super() }}
{%- endblock -%}

{%- block content -%}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Hello, World!</h1>
    <p class="govuk-body-l">This is a template <a href="https://flask.palletsprojects.com" class="govuk-link">Flask</a>
      app using the <a href="https://frontend.design-system.service.gov.uk/" class="govuk-link">GOV.UK Frontend</a> and
      <a href="https://design-system.service.gov.uk/" class="govuk-link">GOV.UK Design System</a> which is designed to
      get a new project started quicker.
    </p>
    <p class="govuk-body">It is also the reference implementation of two core packages:</p>
    <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
      <li><a class="govuk-link" href="https://github.com/LandRegistry/govuk-frontend-jinja">GOV.UK Frontend Jinja</a>
        which provides Jinja macros of GOV.UK components</li>
      <li><a class="govuk-link" href="https://github.com/LandRegistry/govuk-frontend-wtf">GOV.UK Frontend WTForms</a>
        which provides WTForms widgets to integrate the above Jinja macros into form generation and validation</li>
    </ul>
    <p class="govuk-body">The app is provided intentionally bare, with just the essential parts that all services need,
      such as error pages, accessibility statement, cookie banner, cookie page and privacy notice.</p>

    <h2 class="govuk-heading-m">Features</h2>
    <p class="govuk-body">A number of other packages are used to provide the features listed below with sensible and
      best-practice defaults:</p>
    <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
      <li>Asset management</li>
      <li>Cache busting</li>
      <li>Form generation and validation</li>
      <li>Form error handing</li>
      <li>Flash messages</li>
      <li>CSRF protection</li>
      <li>HTTP security headers</li>
      <li>Content Security Policy (CSP)</li>
      <li>Response compression</li>
      <li>Rate limiting</li>
    </ul>

    <h2 class="govuk-heading-m">Documentation</h2>
    <p class="govuk-body">Detailed documentation on the features listed above and the next steps to start building out your app on top of this template is on <a class="govuk-link"
        href="https://github.com/LandRegistry/govuk-frontend-flask#readme">GitHub</a></p>
  </div>
</div>
{%- endblock -%}

app/templates/main/privacy.html
{%- extends "base.html" -%}

{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}

{%- block pageTitle -%}Privacy notice – {{config['SERVICE_NAME']}} – GOV.UK{%- endblock -%}

{%- block beforeContent -%}
  {{ super() }}
  {{ govukBackLink({
    'text': "Back",
    'href': url_for('main.index')
  }) }}
{%- endblock -%}

{%- block content -%}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        {{ super() }}
        <h1 class="govuk-heading-xl">Privacy notice</h1>
    </div>
</div>
{%- endblock -%}